package com.vts.ems.pis.dao;

import java.time.LocalDate;
import java.util.List;

import com.vts.ems.Admin.model.LoginPasswordHistory;
import com.vts.ems.login.Login;
import com.vts.ems.model.EMSNotification;
import com.vts.ems.pis.dto.CHSSExclusionFormDto;
import com.vts.ems.pis.model.AddressEmec;
import com.vts.ems.pis.model.AddressNextKin;
import com.vts.ems.pis.model.AddressPer;
import com.vts.ems.pis.model.AddressRes;
import com.vts.ems.pis.model.DivisionMaster;
import com.vts.ems.pis.model.EmpFamilyDetails;
import com.vts.ems.pis.model.EmpStatus;
import com.vts.ems.pis.model.Employee;
import com.vts.ems.pis.model.EmployeeDetails;
import com.vts.ems.pis.model.EmployeeDesig;
import com.vts.ems.pis.model.PisCadre;
import com.vts.ems.pis.model.PisCatClass;
import com.vts.ems.pis.model.PisCategory;
import com.vts.ems.pis.model.PisEmpFamilyForm;
import com.vts.ems.pis.model.PisPayLevel;

public interface PisDao {

	public List<Object[]> EmployeeDetailsList(String LoginType, String Empid) throws Exception;
	public Object[] EmployeeDetails(String empid) throws Exception;
	public List<DivisionMaster> DivisionList() throws Exception;
	public List<EmployeeDesig> DesigList() throws Exception;
	public List<PisPayLevel> PayLevelList() throws Exception;
	public List<PisCadre> PisCaderList() throws Exception;
	public List<PisCatClass> PisCatClassList() throws Exception;
	public List<PisCategory> PisCategoryList() throws Exception;
	public List<EmpStatus> EmpStatusList() throws Exception;
	public long EmployeeAddSubmit(Employee emp) throws Exception;
	public long EmployeeEditSubmit(Employee emp) throws Exception;
	public long EmployeeDetailsAddSubmit(EmployeeDetails emp) throws Exception;
	public long EmployeeDetailsEditSubmit(EmployeeDetails emp) throws Exception;
	public EmployeeDetails getEmployee(String empno) throws Exception;
	public EmployeeDetails getEmployeeDetailsData(String empno) throws Exception;
	public Employee getEmp(String empid) throws Exception;
	public int PunchcardList(String value)throws Exception;
	public long getempno()throws Exception;
	public String PhotoPath(String empid)throws Exception;
	public int PhotoPathUpdate(String Path, String empno) throws Exception;
	public List<Object[]> LoginMasterList() throws Exception;
	public List<Object[]> getEmpList()throws Exception;
	public List<Object[]> getLoginTypeList()throws Exception;
	public int UserManagerDelete(String username , String loginid)throws Exception;
	public int UserNamePresentCount(String UserName)throws Exception;
	public Long UserManagerAdd(Login login) throws Exception;
	public Login getLoginEditData(Long LoginId)throws Exception;
	public int UserManagerEdit(Login login)throws Exception;
	public List<Object[]> getFamilyMembersList(String empid)throws Exception;
	public Object[] GetEmpData(String empid)throws Exception;
	public List<Object[]> getFamilyRelation()throws Exception;
	public List<Object[]> getFamilyStatus()throws Exception;
	public Long AddFamilyDetails(EmpFamilyDetails Details) throws Exception;
	public int DeleteMeber(String familyid,String Username)throws Exception;
	public EmpFamilyDetails	getMemberDetails(String familyid)throws Exception;
	public Long EditFamilyDetails(EmpFamilyDetails Details) throws Exception;
	public EmpFamilyDetails getMember(String familyid) throws Exception;
	public Object[] getPerAddress(String Empid)throws Exception;
	public List<Object[]> getStates ()throws Exception;
	public List<Object[]> GetAllEmployee()throws Exception;
	public Long AddPerAddress(AddressPer peraddress)throws Exception;
	public AddressPer getPerAddressData(String empid)throws Exception;
	public Long EditPerAddress(AddressPer address) throws Exception;
	public AddressPer getPeraddress(long addressid) throws Exception ;
	public List<Object[]> getResAddress(String empid)throws Exception;
	public Object[]  getKinAddress(String empid)throws Exception;
	public Object[]  getEmeAddress(String empid)throws Exception;
	public Long AddResAddress(AddressRes resaddress)throws Exception;
	public AddressRes getResAddressData(String addressid)throws Exception;
	public Long EditResAddress(AddressRes address) throws Exception;
	public int deleteResAdd(String addresid,String Username)throws Exception;
	public Long AddNextAddress(AddressNextKin nextaddress)throws Exception;
	public Long EditNextKinAddress(AddressNextKin address)throws Exception;
	public AddressNextKin getNextKinaddress(long addressid) throws Exception;
	public AddressNextKin getNextKinAddressData(String empid)throws Exception;
	public Long AddEmecAddress(AddressEmec Emecaddress)throws Exception;
	public AddressEmec getEmecaddress(long addressid) throws Exception;
	public Long EditEmecAddress(AddressEmec address) throws Exception ;
	public List<Object[]> ReqEmerAddajax(String Empid) throws Exception ;
	public AddressEmec getEmecAddressData(String empid)throws Exception;
	public String OldPassword(String UserId) throws Exception;
	public List<Object[]> AuditStampingList(String Username,String Fromdate,String Todate) throws Exception;
	public int PasswordChange(String OldPassword, String NewPassword ,String UserName, String ModifiedDate,String username)throws Exception;
	public Object[] EmployeeEmeAddressDetails(String empid) throws Exception;
	public Object[] EmployeeNextAddressDetails(String empid) throws Exception;
	public Object[] EmployeePerAddressDetails(String empid) throws Exception;
	public List<Object[]> EmployeeResAddressDetails(String empid) throws Exception;
	public List<Object[]> getFamilydetails(String empid) throws Exception;
	public int ResetPassword(String loginid, String password,String UserName )throws Exception;
	public Object[] GetEmpPhoneNo(String loginid) throws Exception;
	public List<Object[]> GetEmployeeList()throws Exception;
	public long loginHisAddSubmit(LoginPasswordHistory model) throws Exception;
	public Object[] GetEmpDetails(String empid)throws Exception;
	public List<Object[]> UpdateAndGetList(Long empId, String newSeniorityNumber)throws Exception;
	public int UpdateAllSeniority(Long empIdL, Long long1)throws Exception;
	public EmpFamilyDetails getFamilyMemberModal(String familydetailsid) throws Exception;
	public List<Object[]> FamMemFwdEmpList() throws Exception;
	public List<Object[]> GetFormMembersList(String empid,String formid) throws Exception;
	public Object[] getEmployeeInfo(String empid) throws Exception;
	public Object[] employeeResAddr(String empid) throws Exception;
	public List<Object[]> familyRelationList() throws Exception;
	public Object[] RelationshipData(String relationid) throws Exception;
	public Object[] getMemberdata(String familydetailid) throws Exception;
	public List<Object[]> EmpFamFormsList(String empid, String status) throws Exception;
	public int FamilyMemIncConfirm(String formid, String empid, String username) throws Exception;
	public long EmpFamilyFormAdd(PisEmpFamilyForm form) throws Exception;
	public Object[] GetFamFormData(String familyformid) throws Exception;
	public int FamilyMemberDelete(String familydetailsid) throws Exception;
	public int EmpBloodGropuEdit(String empno, String bloodgroup) throws Exception;
	public List<Object[]> GetEmployeeLoginData(String loginid) throws Exception;
	public long NotificationAdd(EMSNotification notification) throws Exception;
	public List<Object[]> loginTypeEmpData(String logintype) throws Exception;
	public PisEmpFamilyForm getPisEmpFamilyForm(String familyformid) throws Exception;
	public long UpdateMemberStatus(PisEmpFamilyForm famform) throws Exception;
	public List<Object[]> EmpFamMembersList(String empid) throws Exception;
	public List<Object[]> GetExcFormMembersList(String formid) throws Exception;
	public int AddMemberToExcForm(CHSSExclusionFormDto formdto) throws Exception;
	
}
