package com.vts.ems.leave.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LeaveHolidayWorkingday generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="leave_holiday_workingday")
@XmlRootElement
public class LeaveHolidayWorkingday implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="HolidayId")
	private int holidayId;
	@Column(name="HOLIDATE")
	private Date holidate;
	@Column(name="HOLINAME")
	private String holiname;
	@Column(name="HOLITYPE")
	private Character holitype;

	public LeaveHolidayWorkingday() {
	}

	public LeaveHolidayWorkingday(Date holidate) {
		this.holidate = holidate;
	}

	public LeaveHolidayWorkingday(Date holidate, String holiname, Character holitype) {
		this.holidate = holidate;
		this.holiname = holiname;
		this.holitype = holitype;
	}

	public int getHolidayId() {
		return this.holidayId;
	}

	public void setHolidayId(int holidayId) {
		this.holidayId = holidayId;
	}

	public Date getHolidate() {
		return this.holidate;
	}

	public void setHolidate(Date holidate) {
		this.holidate = holidate;
	}

	public String getHoliname() {
		return this.holiname;
	}

	public void setHoliname(String holiname) {
		this.holiname = holiname;
	}

	public Character getHolitype() {
		return this.holitype;
	}

	public void setHolitype(Character holitype) {
		this.holitype = holitype;
	}

	@Override
	public String toString() {
		return "LeaveHolidayWorkingday [holidayId=" + holidayId + ", holidate=" + holidate + ", holiname=" + holiname
				+ ", holitype=" + holitype + "]";
	}

	
}
